{{- if and .Values.medialit.enabled .Values.medialit.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "courselit.fullname" . }}-medialit-secrets
  labels:
    {{- include "courselit.medialit.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.medialit.externalSecrets.secretStore.name }}
    kind: {{ .Values.medialit.externalSecrets.secretStore.kind }}
  target:
    name: {{ include "courselit.fullname" . }}-medialit-secrets
    creationPolicy: Owner
  data:
    {{- if .Values.medialit.externalSecrets.s3Credentials.enabled }}
    - secretKey: aws-access-key-id
      remoteRef:
        key: {{ .Values.medialit.externalSecrets.s3Credentials.keyRef }}
    - secretKey: aws-secret-access-key
      remoteRef:
        key: {{ .Values.medialit.externalSecrets.s3Credentials.secretRef }}
    {{- end }}
    {{- if .Values.medialit.externalSecrets.cloudfrontPrivateKey.enabled }}
    - secretKey: cloudfront-private-key
      remoteRef:
        key: {{ .Values.medialit.externalSecrets.cloudfrontPrivateKey.keyRef }}
    {{- end }}
{{- end }}
