{{- if and .Values.medialit.enabled .Values.medialit.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "courselit.medialit.serviceAccountName" . }}
  labels:
    {{- include "courselit.medialit.labels" . | nindent 4 }}
  {{- with .Values.medialit.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
