{{- if .Values.medialit.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "courselit.fullname" . }}-medialit
  labels:
    {{- include "courselit.medialit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.medialit.service.type }}
  ports:
    - port: {{ .Values.medialit.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "courselit.medialit.selectorLabels" . | nindent 4 }}
{{- end }}
