apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "courselit.fullname" . }}-app
  labels:
    {{- include "courselit.app.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.app.config.nodeEnv | quote }}
  PORT: {{ .Values.app.port | quote }}
  {{- if .Values.app.smtp.host }}
  SMTP_HOST: {{ .Values.app.smtp.host | quote }}
  SMTP_PORT: {{ .Values.app.smtp.port | quote }}
  SMTP_USER: {{ .Values.app.smtp.user | quote }}
  SMTP_FROM: {{ .Values.app.smtp.from | quote }}
  {{- end }}
