apiVersion: v1
kind: Service
metadata:
  name: {{ include "courselit.fullname" . }}-app
  labels:
    {{- include "courselit.app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "courselit.app.selectorLabels" . | nindent 4 }}
