{{- if .Values.app.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "courselit.fullname" . }}-http
  labels:
    {{- include "courselit.app.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.app.gateway.gatewayClassName }}
      kind: Gateway
  hostnames:
    {{- range .Values.app.gateway.hostnames }}
    - {{ . | quote }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "courselit.fullname" . }}-app
          port: {{ .Values.app.service.port }}
{{- end }}
