{{- if .Values.queue.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "courselit.fullname" . }}-queue
  labels:
    {{- include "courselit.queue.labels" . | nindent 4 }}
spec:
  type: {{ .Values.queue.service.type }}
  ports:
    - port: {{ .Values.queue.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "courselit.queue.selectorLabels" . | nindent 4 }}
{{- end }}
